version: "3.7"

services:
  db-mysql:
    image: "mysql:5.6"
    container_name: dbmysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql


  app:
    depends_on:
      - db-mysql
    image: "yassinehk840/kaddem"
    container_name: springbootapp
    build: 'C:\Users\hkiri\OneDrive\Bureau\Esprit\Devops\ProjetDevops\kaddem'
    restart: unless-stopped
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/kadem?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=

networks:
  springapimysql-net:

volumes:
  db: